"ABOUT" alignment fix
kreiva-iiitv/keriva-frontend-2020 pull request #14
Opened 2020-12-29 11:53 UTC by jatin0814

![Screenshot (18)](https://user-images.githubusercontent.com/56168174/103282088-98d9e300-49fa-11eb-87d2-0e8adcfc7347.png)

2020-12-29 11:54 UTC, jatin0814 commented
@prathmeshkhandelwal1  check kar le

2020-12-29 20:30 UTC, prathmeshkhandelwal1 requested changes
@jatin0814  make about heading small and also the size of box is bit large.

2020-12-29 20:30 UTC, prathmeshkhandelwal1 commented on src/Component/HomeComponents/About/About.css
>      border-bottom: 7px solid #821169;
make this width 3px

2020-12-29 20:30 UTC, prathmeshkhandelwal1 commented on src/Component/HomeComponents/About/About.css
> +  .ABOUT {
width and height is large as compared to gallery header.

2020-12-29 20:31 UTC, prathmeshkhandelwal1 commented on src/Component/HomeComponents/About/About.css
>      border-bottom: 7px solid #821169;
> make this width 3px

border-bottom property

2020-12-30 08:10 UTC, jatin0814 commented
![Screenshot (20)](https://user-images.githubusercontent.com/56168174/103338443-7bf9ea00-4aa4-11eb-9ee8-ba8315adb06f.png)
@prathmeshkhandelwal1 now?

2021-01-02 08:49 UTC, prathmeshkhandelwal1 approved these changes

2021-01-02 08:49 UTC, merged