navbar fixed
kreiva-iiitv/keriva-frontend-2020 pull request #16
Opened 2021-01-03 18:32 UTC by sidharth3000

2021-01-03 18:37 UTC, prathmeshkhandelwal1 requested changes

2021-01-03 18:37 UTC, prathmeshkhandelwal1 commented on src/Component/Header/Header.css
>      padding-top: 6%;
padding percentage me mat rkh

2021-01-03 18:37 UTC, prathmeshkhandelwal1 commented on src/Component/Header/Header.css
> +    padding-right: 3.5%;
same goes here

2021-01-05 10:23 UTC, ShivanshKumar commented
@sidharth3000  Put a div inside the header, and apply class "tabs" to it, remove the class from the header
Also, put all the anchor tags in a div. 😅

2021-01-06 19:04 UTC, merged